tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
#### brew
brew "fish"
brew "git"
brew "wget"
brew "jq"
# brew "vim"
# brew "macvim"
# brew "dnsmasq"
#### cask
cask "macvim"
cask "1password"
cask "google-chrome"
cask "google-japanese-ime"
cask "firefox"
cask "dropbox"
cask "iterm2"
cask "visual-studio-code"
cask "docker"
cask "alfred"
cask "notion"
cask "evernote"
cask "cheatsheet"
cask "sourcetree"
cask "forklift"
# cask "bettertouchtool"
# cask "cyberduck"
# cask "insomnia"
# cask "pdf-expert"
# cask "imageoptim"
# cask "appcleaner"
# cask "slack"
